stages:
  - build
  - test
  - publish
  - release
  - database

default:
  tags:
    - build-gcp

variables:
  CONTAINER_REGISTRY: ${CI_REGISTRY_IMAGE}/application

build:
  stage: build
  script:
    - cp .env.example .env
    - docker build -t $CONTAINER_REGISTRY:${CI_COMMIT_TAG} -t $CONTAINER_REGISTRY:latest -f ./ops/Dockerfile .
  except:
    - branches
  artifacts:
    paths:
      - .env
    expire_in: 1 days
    when: always

sonarqube-check:
  stage: test
  dependencies:
    - build
  tags:
    - tools-gcp
  image: 
    name: sonarsource/sonar-scanner-cli:5.0
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - sonar-scanner
  only:
    - /^([A-Za-z0-9.]+)$/
    - merge_requests
  # allow_failure: false
  except:
    - branches

report-sonar-to-merge-id:
  stage: test
  dependencies:
    - sonarqube-check
  tags:
    - tools-gcp
  script:
    - PROJECT_ID=$CI_PROJECT_ID
    - MERGE_IID=$CI_MERGE_REQUEST_IID
    - KEY=$KEY SONAR_TOKEN=$sonar_access_token repopo_token=$repopo_token PROJECT_ID=$PROJECT_ID MERGE_IID=$MERGE_IID bash -c 'sed -i "1s/^/project_id=$PROJECT_ID merge_iid=$MERGE_IID key=$KEY sonar_token=$sonar_access_token repopo_token=$repopo_token /" ./ops/report.sh'
    - apt-get update -qy  # Install curl
    - apt-get install -y curl
    - bash ./ops/report.sh
    # - cat report.sh
  except:
    - branches
  only:
    - merge_requests
  needs:
    - job: sonarqube-check
  # when: manual

publish:
  stage: publish
  dependencies:
    - sonarqube-check
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CONTAINER_REGISTRY:${CI_COMMIT_TAG}
    - docker push $CONTAINER_REGISTRY:latest
  except:
    - branches
  artifacts:
    paths:
      - .env
    expire_in: 1 days
    when: always

staging:
  stage: release
  dependencies:
    - publish
  variables:
    GIT_STRATEGY: none
    ENVI: staging
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo "$ENV_STAGING" > "$(pwd)/.env"
    - echo "$NOTIFIER" > "$(pwd)/notifier.sh"
    - echo "$DOCKER_COMPOSE_NGINX" | base64 --decode > "$(pwd)/docker-compose.yml"
    - docker compose pull application && docker compose up -d --force-recreate
    - docker image prune -f
    - bash notifier.sh
  only:
    - /^([A-Za-z0-9.-]+)$/
  tags:
    - staging-gcp
  except:
    - branches
  artifacts:
    paths:
      - .env
      - docker-compose.yml
    expire_in: 1 days
    when: always

production:
  stage: release
  dependencies:
    - publish
  variables:
    GIT_STRATEGY: none
    ENVI: production
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo "$ENV_RELEASE" > "$(pwd)/.env"
    - echo "$NOTIFIER" > "$(pwd)/notifier.sh"
    - echo "$DOCKER_COMPOSE_NGINX" | base64 --decode > "$(pwd)/docker-compose.yml"
    - docker compose pull application && docker compose up -d --force-recreate
    - docker image prune -f
    - bash notifier.sh
  tags:
    - production-gcp
  only:
    - /^([A-Za-z0-9.]+)$/
  except:
    - branches
  artifacts:
    paths:
      - .env
      - docker-compose.yml
    expire_in: 1 days
    when: always
  when : manual

staging-migration:
  stage: database
  dependencies:
    - staging
  script:
    - docker compose exec -T --user root application go run . db migrate
  tags:
    - staging-gcp
  only:
    - /^([A-Za-z0-9.-]+)$/
  except:
    - branches
  artifacts:
    paths:
      - .env
    expire_in: 1 days
    when: always
  needs:
    - job: staging

production-migration:
  stage: database
  dependencies:
    - production
  script:
    - docker compose exec -T --user root application go run . db migrate
  tags:
    - production-gcp
  only:
    - /^([A-Za-z0-9.]+)$/
  except:
    - branches
  artifacts:
    paths:
      - .env
    expire_in: 1 days
    when: always
  needs:
    - job: production

staging-seeder:
  stage: database
  dependencies:
    - staging
  script:
    - docker compose exec -T --user root application go run . db seed
  tags:
    - staging-gcp
  only:
    - /^([A-Za-z0-9.-]+)$/
  except:
    - branches
  artifacts:
    paths:
      - .env
      - storage/firebase-admin-sdk.json
    expire_in: 1 days
    when: always
  needs:
    - job: staging
  when: manual